### ISSUE TITLE
Sequence contains no elements exception.

### ISSUE THREAD

**Issue by azeebazy** [ssinno28/Lucene.Net.DocumentMapper#3]
I am getting the following exception while I try to map an object to a document.

```
_mapper.Map(obj)' threw an exception of type 'System.InvalidOperationException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233079
    HelpLink: null
    InnerException: null
    Message: "Sequence contains no elements"
    Source: "System.Linq"
    StackTrace: "   at System.Linq.ThrowHelper.ThrowNoElementsException()\r\n   at Lucene.Net.DocumentMapper.DocumentMapper.GetFields(Object source, IList`1 fields, String prefix)\r\n   at Lucene.Net.DocumentMapper.DocumentMapper.Map(Object source)"
    TargetSite: {Void ThrowNoElementsException()}
```

I suspect the usage of Single in GetFields method. I have a property of type byte[].
Any way to fix this issue or any workaround.

**Comment by skullycheese** [comment]
Can you post the C# classes that are used when you get this mapping exception?

**Comment by azeebazy** [comment]
Below class probably would throw exception.

```
public class MyClass
{
    public byte[] Data { get; set; }
}
```

**Comment by skullycheese** [comment]
Okay this has been fixed, byte[] fields now store properly, although you won't be able to search against them since its just random binary data. 

You can now use arrays as well, before we just supported the use of Lists, all collection types should be supported now. Please test this out and let me know if you have any issues.

**Comment by azeebazy** [comment]
Thanks for the fix. Will the fix works for all type of Arrays or just byte array. Saw the code changes in ReflectionHelper.cs explicitly checking for byte[].

**Comment by skullycheese** [comment]
It will work for all types of arrays now. The byte[] is treated differently than a normal array, which is why it is singled out.

**Comment by skullycheese** [comment]
This issue has been addressed and is being closed due to inactivity.
